spring:
#  security:
 #   user:
  #    name: Manuel
    #  password: 123
   #   roles: "USER"
  datasource:
    url: jdbc:postgresql://localhost:5432/exampledb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
